[package]
name = "nft-contract-tools"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "5.24.0"
near-sdk-contract-tools = "3.0.2"

[dev-dependencies] 
near-sdk = { version = "5.24.0", features = ["unit-testing"] }
near-sandbox = "0.3"
near-api = "0.8"
cargo-near-build = "=0.10"
tokio = { version = "1.48.0", features = ["full"] }
testresult = "0.4.1"
anyhow = "1.0"
near-contract-standards = "5.24.0"
# This is temporary fix for the build error since those crates with a higher version require a higher version of Rust compiler (1.88.0)
cargo-platform = "=0.3.1"
