name: Tests
on: push
jobs:
  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
    
      - name: Install cargo-near
        run: cargo install cargo-near

      - name: "Install stable Rust version"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.86.0
          default: true
          target: wasm32-unknown-unknown

      - name: Install and test modules
        run: |
          cargo test
